Repository snapp-incubator/crafting-table, pull requests merged in 2022-08, with the labels that each got.

#33 fix bug in adding additional comments in test file
  CHANGELOG.md
  internal/repository/functions.go
Labels: bug

#36 Create ct manifest 📖
  CHANGELOG.md
  cmd/generate.go
  cmd/ui.go
  example/ct_manifest.yaml
  example/dst/builtin.go
  example/dst/example.go
  example/dst/example2.go
  example/dst/example2_test.go
  example/dst/example_test.go
  internal/app/app.go
  internal/assets/sqlx/syntax_tamplate.go
  internal/assets/sqlx/test_template.go
  internal/parser/extract_variables.go
  internal/repository/functions.go
  internal/repository/generator.go
  internal/structure/struct.go
Labels: bug, enhancement

#37 Add manifest command 🛞
  CHANGELOG.md
  cmd/generate.go
  cmd/manifest.go
  cmd/root.go
Labels: feature

#38 Add selected tags flag to manifest command ⛳
  CHANGELOG.md
  cmd/manifest.go
  example/dst/example.go
  example/dst/example2.go
  example/dst/example2_test.go
  example/dst/example_test.go
  internal/app/app.go
  internal/parser/extract_variables.go
Labels: feature

#35 27-Remove-app-package ❎
  .gitignore
  CHANGELOG.md
  cmd/generate.go
  cmd/manifest.go
  cmd/root.go
  go.mod
  go.sum
  internal/assets/ascii_art.go
  internal/repository/repository.go
Labels: enhancement
