Repository snapp-incubator/crafting-table, pull requests merged in 2022-11, with the labels that each got.

#48 improve: remove unnecessary Rows in SQL tests 🪶
  CHANGELOG.md
  internal/assets/sqlx/test_template.go
Labels: enhancement

#52 add swagger
  internal/server/swagger.yml
Labels: documentation

#54 Add swagger
  internal/server/swagger.yml
Labels: documentation

#55 Add aggregate 🖼️
  CHANGELOG.md
  cmd/generate.go
  cmd/manifest.go
  example/ct_manifest.yaml
  example/dst/example.go
  example/dst/example2_test.go
  example/dst/example_join.go
  example/dst/example_join_test.go
  example/dst/example_test.go
  internal/assets/sqlx/syntax_tamplate.go
  internal/assets/sqlx/test_template.go
  internal/repository/functions.go
  internal/repository/generator.go
  internal/repository/repository.go
  internal/structure/struct.go
Labels: feature

#56 🛟 Add server
  cmd/root.go
  cmd/serve.go
  go.mod
  go.sum
  internal/repository/repository.go
  internal/server/handlers/db_generate_manifest_and_repo.go
  internal/server/handlers/db_get_fields.go
  internal/server/handlers/db_get_structs.go
  internal/server/routes.go
  internal/server/server.go
  internal/server/swagger.yml
  internal/structure/struct.go
Labels: feature

#57 replace sprintf with text templates
  CHANGELOG.md
  internal/assets/sqlx/syntax_tamplate.go
Labels: enhancement

#58 ⚙️ Add query builder layer
  CHANGELOG.md
  go.mod
  go.sum
  internal/query/build.go
Labels: feature

#59 🔨 Add function builder layer
  CHANGELOG.md
  internal/function/build.go
  internal/function/sqlx.go
Labels: enhancement, feature

#60 🎳 Refactor layers and merge them
  CHANGELOG.md
  cmd/generate.go
  cmd/manifest.go
  cmd/root.go
  example/ct_manifest.yaml
  example/dst/.gitkeep
  example/dst/builtin.go
  example/dst/example.go
  example/dst/example2.go
  example/dst/example2_test.go
  example/dst/example_join.go
  example/dst/example_join_test.go
  example/dst/example_test.go
  example/src/example.go
  example/src/repositories.yml
  godepgraph.png
  integration_test.sh
  internal/assets/ascii_art.go
  internal/assets/assets.go
  internal/assets/sqlx/syntax_tamplate.go
  internal/assets/sqlx/test_template.go
  internal/build/generator.go
  internal/build/query_builder.go
  internal/build/sqlx_function_builder.go
  internal/function/sqlx.go
  internal/parser/extract_variables.go
  internal/repository/functions.go
  internal/repository/generator.go
  internal/repository/repository.go
  internal/structure/struct.go
  logo.jpeg
Labels: enhancement, feature

#69 Custom function name
  CHANGELOG.md
  internal/build/generator.go
  internal/build/query_builder.go
  internal/build/sqlx_function_builder.go
Labels: feature

#71 66-add-database-type-to-layer
  CHANGELOG.md
  internal/build/generator.go
  internal/build/query_builder.go
  internal/build/sqlx_function_builder.go
Labels: enhancement

#75 72-order-by-in-build-query-layer
  CHANGELOG.md
  internal/build/query_builder.go
Labels: bug
