Repository snapp-incubator/crafting-table, pull requests merged in 2023-01, with the labels that each got.

#82 Update doc
  .github/README.md
  .github/docs/manifest.md
  CHANGELOG.md
  README.md
Labels: documentation

#79 👋🏻 64 add insert function builder
  CHANGELOG.md
  go.mod
  go.sum
  internal/build/generator.go
  internal/build/query_builder.go
  internal/build/sqlx_function_builder.go
Labels: feature

#83 📝 update docs and remove some files
  .github/CONTRIBUTING.md
  .github/LICENSE.md
  .github/docs/manifest.md
  Makefile
  internal/.gitkeep
Labels: documentation, enhancement

#62 add query builder generator
  .github/README.md
  .github/docs/query-builder-generator.md
  .gitignore
  CHANGELOG.md
  cmd/query_builder.go
  cmd/root.go
  go.mod
  go.sum
  internal/querybuilder/generator.go
  internal/querybuilder/templates.go
Labels: feature
